export const AUTH_ATTEMPTING = 'AUTH_ATTEMPTING';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';

export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
export const PROFILE_FETCHED = 'PROFILE_FETCHED';


export const ADD_ERROR = 'ADD_ERROR';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';


export const FETCHING_CARD = 'FETCHING_CARD';
export const FETCHING_SUCCESS = 'FETCHING_SUCCESS';
export const FETCHING_FAILED = 'FETCHING_FAILED';

export const FETCHING_ORDER_DETAILS = 'FETCHING_ORDER_DETAILS';
export const FETCHING_ORDER_DETAILS_SUCCESS = 'FETCHING_ORDER_DETAILS_SUCCESS';
export const FETCHING_ORDER_DETAILS_FAILED = ' FETCHING_ORDER_DETAILS_FAILED';
